[package]
name = "cfdyndns"
version = "0.0.1"
authors = ["Cole Mickens <cole.mickens@gmail.com>"]

[dependencies]
env_logger = "^0.3"
hyper = "^0.10"
hyper-native-tls = "0.2.2"
log = "^0.3"
serde = "^0.8"
serde_json = "^0.8"
trust-dns = "^0.12"

[replace."backtrace:0.2.3"]
path = "./backtrace-rs"

